import tkinter

class ViewRegister():
    def __init__(self,root):
        self.learningCompletedLabel = tkinter.Label(root, text="Learning completed.", borderwidth=0, bg="green", fg="white")
        self.sideCameraLabel = tkinter.Label(root, borderwidth=0)
        self.registrationDoneButton = tkinter.Button(root, text='Done', width=10, relief="flat", bg="white", font="tahoma")
        self.registrationCancelButton = tkinter.Button(root, text='Cancel', width=10, relief="flat", bg="white", font="tahoma")
        self.aButton = tkinter.Button(root, text='A', width=1, relief="flat", bg="white", font="tahoma")
        self.bButton = tkinter.Button(root, text='B', width=1, relief="flat", bg="white", font="tahoma")
        self.cButton = tkinter.Button(root, text='C', width=1, relief="flat", bg="white", font="tahoma")
        self.dButton = tkinter.Button(root, text='D', width=1, relief="flat", bg="white", font="tahoma")
        self.eButton = tkinter.Button(root, text='E', width=1, relief="flat", bg="white", font="tahoma")
        self.fButton = tkinter.Button(root, text='F', width=1, relief="flat", bg="white", font="tahoma")
        self.gButton = tkinter.Button(root, text='G', width=1, relief="flat", bg="white", font="tahoma")
        self.hButton = tkinter.Button(root, text='H', width=1, relief="flat", bg="white", font="tahoma")
        self.iButton = tkinter.Button(root, text='I', width=1, relief="flat", bg="white", font="tahoma")
        self.jButton = tkinter.Button(root, text='J', width=1, relief="flat", bg="white", font="tahoma")
        self.kButton = tkinter.Button(root, text='K', width=1, relief="flat", bg="white", font="tahoma")
        self.lButton = tkinter.Button(root, text='L', width=1, relief="flat", bg="white", font="tahoma")
        self.mButton = tkinter.Button(root, text='M', width=1, relief="flat", bg="white", font="tahoma")
        self.nButton = tkinter.Button(root, text='N', width=1, relief="flat", bg="white", font="tahoma")
        self.oButton = tkinter.Button(root, text='O', width=1, relief="flat", bg="white", font="tahoma")
        self.pButton = tkinter.Button(root, text='P', width=1, relief="flat", bg="white", font="tahoma")
        self.qButton = tkinter.Button(root, text='Q', width=1, relief="flat", bg="white", font="tahoma")
        self.rButton = tkinter.Button(root, text='R', width=1, relief="flat", bg="white", font="tahoma")
        self.sButton = tkinter.Button(root, text='S', width=1, relief="flat", bg="white", font="tahoma")
        self.tButton = tkinter.Button(root, text='T', width=1, relief="flat", bg="white", font="tahoma")
        self.uButton = tkinter.Button(root, text='U', width=1, relief="flat", bg="white", font="tahoma")
        self.vButton = tkinter.Button(root, text='V', width=1, relief="flat", bg="white", font="tahoma")
        self.wButton = tkinter.Button(root, text='W', width=1, relief="flat", bg="white", font="tahoma")
        self.xButton = tkinter.Button(root, text='X', width=1, relief="flat", bg="white", font="tahoma")
        self.yButton = tkinter.Button(root, text='Y', width=1, relief="flat", bg="white", font="tahoma")
        self.zButton = tkinter.Button(root, text='Z', width=1, relief="flat", bg="white", font="tahoma")
        self.backspaceButton = tkinter.Button(root, text='⇐', width=7, relief="flat", bg="white", font="tahoma")
        self.faceNameText = tkinter.Text(root, height = 1, width = 60)