import tkinter

class ViewRegister():
    def __init__(self,root):
        self.learning_completed_label = tkinter.Label(root, text="Learning completed.", borderwidth=0, bg="green", fg="white")
        self.registration_instructions_label = tkinter.Label(root, text="Learning completed.", borderwidth=0, bg="green", fg="white")
        self.side_camera_label = tkinter.Label(root, borderwidth=0)
        self.registration_done_button = tkinter.Button(root, text='Done', width=10, relief="flat", bg="white", font="tahoma")
        self.registration_cancel_button = tkinter.Button(root, text='Cancel', width=10, relief="flat", bg="white", font="tahoma")
        self.a_button = tkinter.Button(root, text='A', width=1, relief="flat", bg="white", font="tahoma")
        self.b_button = tkinter.Button(root, text='B', width=1, relief="flat", bg="white", font="tahoma")
        self.c_button = tkinter.Button(root, text='C', width=1, relief="flat", bg="white", font="tahoma")
        self.d_button = tkinter.Button(root, text='D', width=1, relief="flat", bg="white", font="tahoma")
        self.e_button = tkinter.Button(root, text='E', width=1, relief="flat", bg="white", font="tahoma")
        self.f_button = tkinter.Button(root, text='F', width=1, relief="flat", bg="white", font="tahoma")
        self.g_button = tkinter.Button(root, text='G', width=1, relief="flat", bg="white", font="tahoma")
        self.h_button = tkinter.Button(root, text='H', width=1, relief="flat", bg="white", font="tahoma")
        self.i_button = tkinter.Button(root, text='I', width=1, relief="flat", bg="white", font="tahoma")
        self.j_button = tkinter.Button(root, text='J', width=1, relief="flat", bg="white", font="tahoma")
        self.k_button = tkinter.Button(root, text='K', width=1, relief="flat", bg="white", font="tahoma")
        self.l_button = tkinter.Button(root, text='L', width=1, relief="flat", bg="white", font="tahoma")
        self.m_button = tkinter.Button(root, text='M', width=1, relief="flat", bg="white", font="tahoma")
        self.n_button = tkinter.Button(root, text='N', width=1, relief="flat", bg="white", font="tahoma")
        self.o_button = tkinter.Button(root, text='O', width=1, relief="flat", bg="white", font="tahoma")
        self.p_button = tkinter.Button(root, text='P', width=1, relief="flat", bg="white", font="tahoma")
        self.q_button = tkinter.Button(root, text='Q', width=1, relief="flat", bg="white", font="tahoma")
        self.r_button = tkinter.Button(root, text='R', width=1, relief="flat", bg="white", font="tahoma")
        self.s_button = tkinter.Button(root, text='S', width=1, relief="flat", bg="white", font="tahoma")
        self.t_button = tkinter.Button(root, text='T', width=1, relief="flat", bg="white", font="tahoma")
        self.u_button = tkinter.Button(root, text='U', width=1, relief="flat", bg="white", font="tahoma")
        self.v_button = tkinter.Button(root, text='V', width=1, relief="flat", bg="white", font="tahoma")
        self.w_button = tkinter.Button(root, text='W', width=1, relief="flat", bg="white", font="tahoma")
        self.x_button = tkinter.Button(root, text='X', width=1, relief="flat", bg="white", font="tahoma")
        self.y_button = tkinter.Button(root, text='Y', width=1, relief="flat", bg="white", font="tahoma")
        self.z_button = tkinter.Button(root, text='Z', width=1, relief="flat", bg="white", font="tahoma")
        self.zero_button = tkinter.Button(root, text='0', width=1, relief="flat", bg="white", font="tahoma")
        self.one_button = tkinter.Button(root, text='1', width=1, relief="flat", bg="white", font="tahoma")
        self.two_button = tkinter.Button(root, text='2', width=1, relief="flat", bg="white", font="tahoma")
        self.three_button = tkinter.Button(root, text='3', width=1, relief="flat", bg="white", font="tahoma")
        self.four_button = tkinter.Button(root, text='4', width=1, relief="flat", bg="white", font="tahoma")
        self.five_button = tkinter.Button(root, text='5', width=1, relief="flat", bg="white", font="tahoma")
        self.six_button = tkinter.Button(root, text='6', width=1, relief="flat", bg="white", font="tahoma")
        self.seven_button = tkinter.Button(root, text='7', width=1, relief="flat", bg="white", font="tahoma")
        self.eight_button = tkinter.Button(root, text='8', width=1, relief="flat", bg="white", font="tahoma")
        self.nine_button = tkinter.Button(root, text='9', width=1, relief="flat", bg="white", font="tahoma")
        self.backspace_button = tkinter.Button(root, text='⇐', width=7, relief="flat", bg="white", font="tahoma")
        self.face_name_text = tkinter.Text(root, height = 1, width = 60)